### ISSUE TITLE
配置IP的Server可以访问,配置CF域名的Server不行

### ISSUE THREAD

**Issue by DISSIDIA-986** [gost-x/ShadowsocksX-NG-GostPlugin#10]
相同Server配置,DirectProxy配置IP的Server可以访问,配置CF域名的Server不行 是什么原因?检查Cloudflare DNS Records是正常的,SSL/TLS Overview 页面也正常"Your SSL/TLS encryption mode is Flexible",如何排查呢?

**Comment by DISSIDIA-986** [comment]
```shell
websocat wss://domain.com:443
```
websocat: WebSocketError: WebSocketError: Received unexpected status code (521 <unknown status code>)

**Comment by DISSIDIA-986** [comment]
https://www.hostinger.com/tutorials/error-521
turn on the SSL/TLS Recommender 后解决此问题

**Comment by lewangdev** [comment]
也可以直接在浏览器里面访问这个地址来验证，看看能不能打开：

https://{your_domain}:443/ws

或者

https://{your_ip}:443/ws
