### ISSUE TITLE
Lacking support of Apple Silicon Chip

### ISSUE THREAD

**Issue by jinliangwii** [gost-x/ShadowsocksX-NG-GostPlugin#11]
```
% ./gost-plugin 
zsh: bad CPU type in executable: ./gost-plugin-mwss 
% file ./gost-plugin 
./gost-plugin: Mach-O 64-bit executable x86_64
```

只是想提醒一下大家，这个plugin只能在Intel-based macOS上运行。

**Comment by jinliangwii** [comment]
可以用参考下面的指令生成独立的二进制文件并且支持双平台。
`pyinstaller --onefile --target-arch universal2  gost-plugin.py`

**Comment by lewangdev** [comment]
没有测试过 M1/M2 CPU。如果自己的 MacOS 上有安装 Python3，可以把 `gost-plugin.py` 改名为 `gost-plugin` 并添加执行权限

**Comment by lewangdev** [comment]
M1/M2 CPU Please try:
* [gost-plugin-aarch64.gz](https://github.com/lewangdev/ShadowsocksX-NG-GostPlugin/releases/download/v0.0.2/gost-plugin-aarch64.gz)
* [gost-plugin-mwss-aarch64.gz](https://github.com/lewangdev/ShadowsocksX-NG-GostPlugin/releases/download/v0.0.2/gost-plugin-mwss-aarch64.gz)
