### ISSUE TITLE
不支持mwss协议

### ISSUE THREAD

**Issue by Kahnnn** [gost-x/ShadowsocksX-NG-GostPlugin#4]
通过`mwss`协议起的服务端连不上：`gost -L=mwss://username:password@:443`，
改成`gost -L=wss://username:password@:443`是可以的。
能否考虑支持协议参数配置？

**Comment by lewangdev** [comment]
这个建议很好，我来改一下，谢谢

**Comment by lewangdev** [comment]
使用这个分支安装

https://github.com/lewangdev/ShadowsocksX-NG-GostPlugin/tree/feat/mwss

或者手动下载 https://github.com/lewangdev/ShadowsocksX-NG-GostPlugin/releases/download/v0.0.2/gost-plugin-mwss.gz 到 `${HOME}/Library/Application Support/ShadowsocksX-NG/plugins`, 并且解压为 `gost-plugin-mwss`
