### ISSUE TITLE
Gost.Plugin.go exec was wrong

### ISSUE THREAD

**Issue by sgalcheung** [gost-x/ShadowsocksX-NG-GostPlugin#5]
When I found this plugin, I try to it, but I found source code only supports web socket(ws), but I use HTTP protocol, so I change -F param, than build it, but is don't work, when I look carefully and find goland exec command need separate parameters, [ex](https://stackoverflow.com/a/56280237)

**Comment by sgalcheung** [comment]
#6

**Comment by lewangdev** [comment]
Thank you 💖

PS, The plugin binary in release was produced by rust-lang version.

**Comment by sgalcheung** [comment]
That‘s fine, Another thing is how to support http and websocket protocol, need to discussion

**Comment by lewangdev** [comment]
I have previously considered this question and concluded that the current gost plugin is not fully-featured, making it difficult for the ShadowsocksX-NG client to configure. Additionally, using SS_PLUGIN_OPTIONS to pass more parameters to gost may result in people finding it challenging to configure correctly.
