### ISSUE TITLE
无法连接到服务器

### ISSUE THREAD

**Issue by AdaSongS** [gost-x/ShadowsocksX-NG-GostPlugin#8]
您好，我对计算机各方面的了解几乎空白，最近买了 VPS 想按照您的教程试试看。

我当前的目标是通过 IP 直连实现科学上网，如果成功，再进一步配置域名。我能想到并且可以提供的信息如下：

服务端
- 系统: AlmaLinux OS 8
- gost: 与教程一致

客户端
- 系统：macOS(M1 芯片)
- gost: 与教程一致
- 工具：ShadowsocksX-NG v1.10.0

日常使用的上网工具：ClashX(不知是否存在影响因素，先列一下)

**当前进度**
1. 在 VPS 上开启 gost
<img width="797" alt="image" src="https://user-images.githubusercontent.com/38029725/235299631-59124a4d-e840-4597-b07a-471c715b607d.png">

2. 设定 username:password
<img width="425" alt="image" src="https://user-images.githubusercontent.com/38029725/235300259-5586d434-bfd6-4cff-b6cf-67819dd78097.png">

3. 解压 ShadowsocksX-NG Gost Plugin
- 路径: /Applications/ShadowsocksX-NG.app/Contents/Library/Application Support/ShadowsocksX-NG/plugins/gost-plugin
<img width="561" alt="image" src="https://user-images.githubusercontent.com/38029725/235300659-472d5b04-390e-43ad-98b2-985dd3d63063.png">

**我遇到的问题**
按照 gost 设置的 username:password 输入 ShadowsocksX-NG，无法连接到 VPS
<img width="901" alt="image" src="https://user-images.githubusercontent.com/38029725/235300769-2468fff4-c75c-4bad-9640-0f7446b0fa04.png">

实在很不好意思，什么都不会还硬要搞这个。

**Comment by lewangdev** [comment]
插件客户端推荐用脚本安装，需要把 gost 也要下载一份

**Comment by AdaSongS** [comment]
抱歉，还要继续打扰您。又用脚本安装了一次，尝试访问谷歌，依然无法连接。

1. 客户端当前状态如下。另外我发现点击客户端下拉列表中的 Show Logs 没有任何反应，不知这样是否正常。
<img width="563" alt="image" src="https://user-images.githubusercontent.com/38029725/235339960-ca63dd44-9151-440a-931a-0cb437866e84.png">

2. 服务端的状态如下，没有像其他人那样的连接日志，会跟 vendor preset: disable 有关吗？
![image](https://user-images.githubusercontent.com/38029725/235340027-4feafa4d-d3cb-490f-ba32-81d8bb68cd6f.png)

3. 服务端每个文件都打开看了一下，看起来跟 notebook 里面设置的一致
![image](https://user-images.githubusercontent.com/38029725/235340326-1e3af3eb-8133-41dd-bc67-76853851662f.png)

不知接下来还应该排查哪些问题。

**Comment by lewangdev** [comment]
点击show logs应该会打开 console 查看日志的。排查问题先从server排查

https://ip:443/ws 用浏览器打开这个网址看看是否有响应

**Comment by AdaSongS** [comment]
> 

访问没有响应
<img width="646" alt="image" src="https://user-images.githubusercontent.com/38029725/235341509-736cad3b-0121-4c2f-8f02-04879cc4514c.png">

**Comment by lewangdev** [comment]
> > 
> 
> 
> 
> 访问没有响应
> 
> <img width="646" alt="image" src="https://user-images.githubusercontent.com/38029725/235341509-736cad3b-0121-4c2f-8f02-04879cc4514c.png">
> 
> 

防火墙 iptables 有没有开 443 端口？

**Comment by AdaSongS** [comment]
> 

服务端 iptables 状态是这样的。这是我从 ChatGPT 上问到的命令，不知道是不是这样开启呢？
<img width="565" alt="image" src="https://user-images.githubusercontent.com/38029725/235342612-19b2e6e9-6789-433d-b43b-147b21a8488a.png">

**Comment by lewangdev** [comment]
> > 
> 
> 
> 
> 服务端 iptables 状态是这样的。这是我从 ChatGPT 上问到的命令，不知道是不是这样开启呢？
> 
> <img width="565" alt="image" src="https://user-images.githubusercontent.com/38029725/235342612-19b2e6e9-6789-433d-b43b-147b21a8488a.png">
> 
> 

应该是 INPUT

**Comment by AdaSongS** [comment]
> > > 
> > 
> > 
> > 服务端 iptables 状态是这样的。这是我从 ChatGPT 上问到的命令，不知道是不是这样开启呢？
> > <img alt="image" width="565" src="https://user-images.githubusercontent.com/38029725/235342612-19b2e6e9-6789-433d-b43b-147b21a8488a.png">
> 
> 应该是 INPUT

依然无法访问。我想再确认一下，测试服务端要访问的是 https://{我的 VPS ip}:443/ws 吧？
<img width="586" alt="image" src="https://user-images.githubusercontent.com/38029725/235343853-2d34fbb3-1fd0-406d-89f4-3140f76e24e2.png">

**Comment by lewangdev** [comment]
您用的是哪家的主机？云厂商可能也有防火墙

**Comment by AdaSongS** [comment]
> 

是这个平台 (https://www.racknerd.com/)

我联系平台客服，对方告诉我能 ping 通、可以远程登录服务器，那就是正常的。😂

我在 ChatGPT 的指导下查看了服务端端口的开放情况，看起来也没什么问题，所以会不会是在配置客户端的时候有问题呢？
![image](https://user-images.githubusercontent.com/38029725/235427327-5ea0378f-825c-493e-a905-0b6883f5989f.png)

**Comment by AdaSongS** [comment]
刚得知除了 iptables 以外还有其他防火墙工具，于是逐个进行排查，给 firewalld 工具添加 443 端口后，目前 ip 直连已经可以成功访问 Google（感谢王哥，如果你姓王的话），不过还有一个问题不太懂。

当我访问  https://{我的 VPS ip}:443/ws 时，浏览器提示和服务端记录如下，ChatGPT 告诉我这个代表有风险，我需要进行进一步处理吗？

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/38029725/235438480-e47d97c1-928a-43eb-a263-af703686ce48.png">

![image](https://user-images.githubusercontent.com/38029725/235438589-d86f5750-6945-4e76-a014-8ad291740436.png)

**Comment by AdaSongS** [comment]
所有问题均已解决，谢谢您。

**Comment by lewangdev** [comment]
> 刚得知除了 iptables 以外还有其他防火墙工具，于是逐个进行排查，给 firewalld 工具添加 443 端口后，目前 ip 直连已经可以成功访问 Google（感谢王哥，如果你姓王的话），不过还有一个问题不太懂。
> 
> 当我访问 https://{我的 VPS ip}:443/ws 时，浏览器提示和服务端记录如下，ChatGPT 告诉我这个代表有风险，我需要进行进一步处理吗？
> 
> <img alt="image" width="1023" src="https://user-images.githubusercontent.com/38029725/235438480-e47d97c1-928a-43eb-a263-af703686ce48.png">
> 
> ![image](https://user-images.githubusercontent.com/38029725/235438589-d86f5750-6945-4e76-a014-8ad291740436.png)

没关系的，因为证书是自签的，通过 cloudflare 代理之后就没有这个问题了，也可以从 ZeroSSL.com 或者 Letsencrypt.org 给自己域名申请免费证书来解决
