### ISSUE TITLE
gost-plugins无法被识别

### ISSUE THREAD

**Issue by Sikyy** [gost-x/ShadowsocksX-NG-GostPlugin#9]
![image](https://user-images.githubusercontent.com/65539942/236126150-e931c86b-2d9a-45bd-b1e3-7c086d027ac2.png)
在各类搜索后尝试过修改文本读取编码为GB 18030也无效
查出类型为gost-plugin: application/x-mach-binary; charset=binary
由于最近刚换mac 不太清楚这类问题怎么解决，不好意思啊

**Comment by lewangdev** [comment]
这个是可执行的命令程序，用文本编辑是不能打开的

**Comment by Sikyy** [comment]
哦哦 mac默认识别的就是文本也没后缀啥的，我还以为它就是呢，按道理讲他不应该会被识别为可执行文件的吗...，我找了一圈打开方式好像也没什么可以用的，也试过终端了，有啥解决办法吗，不好意思了（狠狠的磕一个

**Comment by lewangdev** [comment]
不需要打开的，按照说明 [README.md](https://github.com/lewangdev/ShadowsocksX-NG-GostPlugin#%E8%AE%BE%E7%BD%AE) 填好自己的服务器配置就可以用了

**Comment by Sikyy** [comment]
嗯嗯，不是想打开的，因为点击插件选择会弹出界面，双击gost的plugin就会无法打开，所以我试了下直接在插件选择框内输入插件名，其他都按着readme配，失败了，无法ping通，我在【Windows，android】的shadowsocks上都成功了，mac的surge上也可行，我找找原因吧，辛苦啦
